/* This file was generated by SableCC (http://www.sablecc.org/). */

package Prolixa.analysis;

import Prolixa.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTThisIsProgram(TThisIsProgram node);
    void caseTIdentifier(TIdentifier node);
    void caseTThatWouldBeAll(TThatWouldBeAll node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
