/* This file was generated by SableCC (http://www.sablecc.org/). */

package Prolixa.node;

import Prolixa.analysis.*;

@SuppressWarnings("nls")
public final class TThatWouldBeAll extends Token
{
    public TThatWouldBeAll()
    {
        super.setText("That would be all.");
    }

    public TThatWouldBeAll(int line, int pos)
    {
        super.setText("That would be all.");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TThatWouldBeAll(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTThatWouldBeAll(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TThatWouldBeAll text.");
    }
}
