/* This file was generated by SableCC (http://www.sablecc.org/). */

package Prolixa.node;

import Prolixa.analysis.*;

@SuppressWarnings("nls")
public final class TThisIsProgram extends Token
{
    public TThisIsProgram()
    {
        super.setText("This is program");
    }

    public TThisIsProgram(int line, int pos)
    {
        super.setText("This is program");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TThisIsProgram(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTThisIsProgram(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TThisIsProgram text.");
    }
}
